ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Models/MemberGroup.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ViewModels/GroupViewModel.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/AlarmSettingModalView.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingModalView.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/SelectNotificationDay.swift

#9/feat add notification setting modal view theo park

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingModalView.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/SelectNotificationDay.swift

Close #12
내부 변수들을 Setting으로 묶고, 출퇴근 시간의 초기값 설정을 추가했어용

[Refactor] 알림 설정 뷰 내부 구조 리팩토링

---

ChuckchuDrivenDevelopment/CDDWatchApp Watch App/CDDWatchApp Watch App.entitlements
ChuckchuDrivenDevelopment/CDDWatchApp-Watch-App-Info.plist
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/AppDelegate.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopmentApp.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ContentView.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/GoogleService-Info.plist
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Info.plist
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/NotificationTestingView.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/PushNotificationManager.swift

#1/Feat Firebase Cloud Messaging을 이용한 iOS 앱 로컬 푸시 알림을 구현했습니다. 

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopmentApp.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingModalView.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/SelectNotificationDay.swift

MainView UI를 구현했습니다.
추후 스타일은 더 수정해볼 수 있을 것 같아요
Close #21
기존 알림설정모달뷰를 포함하는 새로운 메인 뷰를 구현합니다.

[Feat] MainView UI 구현

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/SplashView.swift

작은 애니메이션이 들어가있는 스플래시 뷰를 만들었습니다.
Close #19
작은 onAppear 애니메이션이 들어가있는 스플래시 뷰를 만들었습니다.

[Feat] 스플래시 뷰 구현

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift

MainView의 스타일 개선
그리고 설정을 성격별로 묶어서 설정의 위계를 개선했습니다.
Close #23
MainView의 스타일을 개선했어요.
설정을 성격별로 묶어서 위계를 개선했어요

[Style] MainView의 스타일을 개선했습니다.

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift

[Style] MainView 스타일 마이너 개선

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/SplashView.swift

스플래시뷰의 애니메이션 타이밍을 개선했습니다.
Close #
스플래시뷰 애니메이션 타이밍을 개선했습니다.

[Feat] SpalshView Animation Timing Improvement

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Assets.xcassets/onBoarding_2.imageset/Contents.json
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/OnBoardingView2.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/OnboardingView1.swift

온보딩뷰1, 2 추가하였습니다.
Close #42
온보딩뷰 1, 2를 만들었어용

[Feat] 온보딩뷰 추가

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/ModalView.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingsCell.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/SelectNotificationDay.swift

Close #44 
햅틱 피드백이 추가되었습니다.
NotificationSettingCell 하단에 메소드를 추가했는데... 나중에 위치를 옮기는 편이 좋을 것 같습니다.

[Feat] 햅틱 피드백 추가

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingsCell.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/ParallaxMotionModifier.swift

Close #46
기기 기울기에 따라 메인뷰가 따라서 기웁니다.

[Feat] AddTilting in MainView

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingsCell.swift

Close #
기존의 로직에서 LongPress가 되었을 때 Modal이 동작하지 않는 버그를 수정했습니다.

[Feat] Haptic Feedback Algorithm Improvement

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingsCell.swift

Close #
- MainView 상단 ‘하루만 끄기’ 토글을 추가했습니다.
- 알림 허용이 되지 않았을 때 MainView를 구현했습니다. 현재는 임의로 토글 활성화 시 보여지는 화면으로 되어 있습니다.

#40/Feat-AddMainViewToggle-Alex

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingsCell.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/ParallaxMotionModifier.swift

Close #55 
메인뷰의 스타일 틸트를 조정했습니다.

[Style] MainView Style Improvement

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingsCell.swift

Close #67
MainView 124번째 줄 주석처리

[Refactor] MainView Minor Bug Fix

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/ParallaxMotionModifier.swift

Close #69 
- 이제 앱 켠 화면을 기준으로 기울임이 감지되어요
- 좀더 잘 움직입니다.
- 앱 이름 꿋꿋으로 바꿨어요

[Feat] Tilting Experience Improvement

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/ParallaxMotionModifier.swift

[Chore] 메인의 머지사항을 가져옵니다.

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopmentApp.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/CharacterAnimation/CharacterAnimation.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Onboardings/OnBoardingView1.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Onboardings/OnBoardingView2.swift

Close #86
Connect OnBoardingView

Connect OnBoardingView

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/ModalView/ModalView.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/ModalView/SelectNotificationDay.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/NotificationSettingsCell.swift

[Style] Weekday Modify

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/CharacterAnimation/CharacterAnimation.swift

Close #91
POSTECH notation correction

[Style] POSTECH notation correction

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/LocalNotificationManager.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/NotificationTitle.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/ModalView/TimePickerRow.swift

Close #95
- 하루 알림 범위 최대 6시간 -> 10시간으로 수정
- 알림 시간 텀, 횟수 관련 로직 수정
- 하루만 끄기 토글 로직 재점검
- 오프닝, 클로징 메세지 베리에이션 적용 확인

[Refactor] 출시 전 마지막 점검 및 버그 수정을 진행했습니다. 

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/xcshareddata/xcschemes/CDDWatchApp Watch App.xcscheme
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/LocalNotificationManager.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/NotificationTitle.swift

Close #97
- opening, closingVariations 사용 중지

[HotFix] 오류가 뜨는 오프닝, 클로징 알림 멘트를 임시적으로 제거했습니다. 

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/SettingInfomationCell.swift

종료시간, 종료시간 -> 시작시간, 종료시간으로 수정했습니다.
Close #102 
종료시간, 종료시간으로 잘못 표기되어있던 정보를 시작시간, 종료시간으로 수정했습니다.

[HotFix] Correcting Incorrect Information

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/LocalNotificationManager.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/DataModels.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/MainView.swift
ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/ModalView/ModalView.swift

Close #107
- 일요일이 설정 요일로 들어오는 버그 수정

[Fix] 주말 요일 값 제외 로직 추가

---

ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj

Close #113
- 설정에서 Landscape option을 비활성화했습니다.

[Feat] Device Landscape Prevention
